FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Coolector

API to collect different taggable items in sets.

## Registration [/register]

### Register [POST]

Create new user simply providing an email and a password

+ Request (application/json)

        {
            "email": "username",
            "password": "password"
        }
        
+ Response 204 (application/json)

+ Response 409 (application/json)

            {
                "message": "Email address already exists."
            }
        
## Authentication [/authenticate]

### Authenticate [POST]

Generate a new JSON Web Token 

+ Request (application/json)

        {
            "email": "username",
            "password": "password"
        }
        
+ Response 200 (application/json)

        {
            "token: "JSON_Web_Token"
        }
            
+ Response 404 (application/json)

        {
            "message": "Email or Password incorrect."
        }

## List and Add Items [/items{?tags}{?limit}{?offset}{?sort}{?q}]

### List items [GET]

+ Parameters
    + tags: tag1,tag2 (string) - Comma delimited tags that you would like to filter the list by
    + q: `custom text` (string) - Search by custom text that may be included in other fields or not
    + limit: 10 (number) - Limit the number or returned results to a fixed number (Default: 10)
    + offset: 0 (number) - Offset to shift the results by. Default: 0
    + sort: `-created_at` (string) - Sort returend list by one field or another or by comma delimited fields in ascending or descending order

+ Request (application/json)
    
    + Headers
    
            Authorization: Bearer JSON_Web_Token

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "url": "http://www.domain.name/resource_normalized_by_server.html",
                "title": "Title 1",
                "image": "http://url/to_image.jpg",
                "created_at": "2015-08-05 08:40:51+01:00",
                "updated_at": "2015-08-06 08:40:51+01:00",
                "tags": [
                    "friends",
                    "cool"
                ]
            },
            {
                "id": 2
                "url": "http://www.domain.name/resource_normalized_by_server_2.html",
                "title": "Title 1",
                "image": "http://url/to_image.jpg",
                "created_at": "2015-08-05 08:40:51+01:00",
                "updated_at": "2015-08-06 08:40:51+01:00",
                "tags": [
                    "friends",
                    "cool"
                ]
            }
        ]
        
+ Response 401 (application/json)

        {
            "message": "Not authenticated."
        }
        
### Create a new item [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer JSON_Web_Token
            
    + Body

            {
                "url": "http://www.domain.name/resource.html",
                "tags": [
                    "friends",
                    "vacation"
                ],
                "collectors": [
                    {
                        "name": "selector",
                        "value":  [
                            {
                                "element": "img",
                                "attributes": {"class": "somclass1", "id": "attr1"},
                                "content": null,
                            }
                        ]
                    },
                    {
                        "name": "in_view_selector",
                        "value":  [
                            {
                                "element": "img",
                                "attributes": {"class": "somclass1", "id": "attr1"},
                                "content": null,
                                "visibility": 0.90
                            }
                        ]
                    }
                ]
            }

+ Response 201 (application/json)

    + Headers
    
            Location: /items/1

    + Body

            {
                "id": 1,
                "url": "http://www.domain.name/resource_normalized_by_server.html",
                "title": "Title 1",
                "image": "http://url/to_image.jpg",
                "created_at": "2015-08-05 08:40:51+01:00",
                "updated_at": "2015-08-05 08:40:51+01:00",
                "tags": [
                    "friends",
                    "vacation"
                ]
            }
            
+ Response 400 (application/json)

        {
            "message": "URL field is required."
        }
            
+ Response 401 (application/json)

        {
            "message": "Not authenticated."
        }
        
## Get, Update or Delete Item [/items/{id}]

+ Parameters
    + id: 1 (number) - ID of an existing item
    
### Get an item by ID [GET]

+ Request (application/json)

    + Headers
    
            Authorization: Bearer JSON_Web_Token

+ Response 201 (application/json)

    + Body
    
            {
                "id": 1,
                "url": "http://www.domain.name/resource_normalized_by_server.html",
                "title": "Title 1",
                "image": "http://url/to_image.jpg",
                "created_at": "2015-08-05 08:40:51+01:00",
                "updated_at": "2015-08-06 08:40:51+01:00",
                "tags": [
                    "friends",
                    "cool"
                ]
            }
            
+ Response 401 (application/json)

        {
            "message": "Not authenticated."
        }
        
+ Response 404 (application/json)

        {
            "message": "Item not found."
        }

### Update an existing item [PUT]

Updating an existing item is restricted in updating only the list of tags that describe that particular item.
The only other option to update the URL is to delete curent item and create a new one.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer JSON_Web_Token
            
    + Body

            {
                "tags": [
                    "friends",
                    "cool"
                ]
            }

+ Response 201 (application/json)

    + Body
    
            {
                "id": 1,
                "url": "http://www.domain.name/resource_normalized_by_server.html",
                "title": "Title 1",
                "image": "http://url/to_image.jpg",
                "created_at": "2015-08-05 08:40:51+01:00",
                "updated_at": "2015-08-06 08:40:51+01:00",
                "tags": [
                    "friends",
                    "cool"
                ]
            }
            
+ Response 400 (application/json)

        {
            "message": "tags field is required."
        }
            
+ Response 401 (application/json)

        {
            "message": "Not authenticated."
        }
        
+ Response 404 (application/json)

        {
            "message": "Item not found."
        }
        
### Delete and existing item [DELETE]

+ Request (application/json)

    + Headers
    
            Authorization: Bearer JSON_Web_Token
            
+ Response 204 (application/json)

+ Response 401 (application/json)

        {
            "message": "Not authenticated."
        }

+ Response 404 (application/json)

        {
            "message": "Item not found."
        }
        
## List Tags [/tags{?q}{?limit}{?offset}{?sort}]

### List tags [GET]

+ Parameters
    + q: `custom text` (string) - Search by custom text that may be included in other fields or not
    + limit: 10 (number) - Limit the number or returned results to a fixed number (Default: 10)
    + offset: 0 (number) - Offset to shift the results by. Default: 0
    + sort: `-tag,created_at` (string) - Sort returend list by one field or another or by comma delimited fields in ascending or descending order

+ Request (application/json)
    
    + Headers
    
            Authorization: Bearer JSON_Web_Token

+ Response 200 (application/json)

        [
            {
                "tag": "friends",
                "created_at": "2015-08-05 08:40:51+01:00"
            },
            {
                "tag": "cool",
                "created_at": "2015-08-05 08:40:51+01:00"
            }
        ]
        
+ Response 401 (application/json)

        {
            "message": "Not authenticated."
        }

## Delete taggs [/tags/{tag}]

### Delete tag [DELETE]

If the tag is not associated with any items it will be deleted.

+ Parameters
    + tag: tag1 (string) - ID of an existing item
    
+ Request (application/json)
    
    + Headers
    
            Authorization: Bearer JSON_Web_Token
            
+ Response 204 (application/json)

+ Response 401 (application/json)

        {
            "message": "Not authenticated."
        }
        

+ Response 404 (application/json)

        {
            "message": "Tag not found."
        }

+ Response 409 (application/json)

        {
            "message": "Tag is in use by another item."
        }